name: CI Pipeline

run-name: Tests triggered by ${{ github.actor }}

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
